/**
 * Copyright (c) 2020-present Beng Tan
 */

const packageJson = require('../../package.json')

export const APP_NAME = 'GigoBooks CE'
export const CREDITS = 'Generated by GigoBooks: Accounting software for solopreneurs and freelancers'
export const VERSION = packageJson.version
export const LICENSE = 'AGPL-3.0'
