/**
 * Copyright (c) 2020-present Beng Tan
 */

const packageJson = require('../../package.json')

export const APP_NAME = "Gig'o'Books CE"
export const CREDITS = "Generated by Gig'o'Books: Non-cloud accounting app for solopreneurs, consultants, freelancers and gig economy workers"
export const VERSION = `${packageJson.version}+${__COMMITDATE__}.${__COMMITHASH__}`
export const LICENSE = 'AGPL-3.0'

export const DEFAULT_PREFERENCES = {}
